### ISSUE TITLE
Badly sized outline 

### ISSUE THREAD

**Issue by rjoly** [msurguy/ladda-bootstrap#34]
Hello !

On expand-left / expand-right buttons, the outline is not completly fabulous, as you can see on joined capture.
![ladda-outline-issue](https://cloud.githubusercontent.com/assets/2973857/4589830/ff46ddc0-5058-11e4-971f-a552550f7e63.png)

We don't have the issue with slide-left / slide-right because of the following code

``` css
.ladda-button[data-style="slide-left"] {
    overflow: hidden;
}
```

Is there any good reason not to write this removing [data-style=...] ? I tried it on demo page and it seems to work fine.

``` css
.ladda-button {
    overflow: hidden;
}
```

**Comment by catmeme** [comment]
you may also want:
```css
button:focus {
    outline:0 !important;
}
```
